name: Build and Publish

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: pip install build

      - name: Build dist
        run: python -m build
        working-directory: ${{ github.workspace }}

      - name: Publish to TestPyPI
        if: github.event.release.prerelease == true
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@v1.8.11
