name: Build and Publish

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade build tools
        run: pip install --upgrade pip setuptools wheel build twine

      - name: Clean previous builds
        run: rm -rf build/ dist/ *.egg-info

      - name: Build distribution
        run: python -m build
        working-directory: ${{ github.workspace }}

      - name: Check distributions
        run: twine check dist/*

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@v1.8.11
